export const API = "{your_Texaglo_api}";
export const IPFS_API = "{your_Texaglo_api}";
export const TEXAGLO = "https://www.texaglo.com";
export const SOL = "your price";
export const CLIENT_ID="your client Id"
export const CLIENT_SECRET="your secret"
export const REDIRECT_URI = "http://127.0.0.1:3000/sdns/deploy"
export const PROXY_URL= "http://localhost:8080/api/subdomain/authenticate"
export const devnetRPC =  "https://api.devnet.solana.com" ;
export const mainnetRPC = "{your_Mainnet rpc}";
export const dev = true;
export const programAddress = "AG9DMWMCDcempq2tQMozgTqcPpAobPStrXu6V5CXTuJm"
export const programAddressForSubdomain = "AG9DMWMCDcempq2tQMozgTqcPpAobPStrXu6V5CXTuJm"
export const royaltyAddress = "your royalty address";
export const treaseryWallet = "your treasury wallet";

export const collectionAuthorityRecord = "your update authority"
export const collectionMint = "your mint address"
export const collectionMetadata ="Metadata address" 
export const collectionMasterEdition = "Master edition address"
export const collectionUpdateAuthority ="your update authority"
